# Generated by Django 4.1.1 on 2022-09-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(default='teacheravatar.jpg', upload_to='teachers'),
        ),
    ]
