# Generated by Django 4.1.1 on 2022-09-15 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='designation',
        ),
        migrations.DeleteModel(
            name='Designation',
        ),
    ]
