# Generated by Django 4.1.1 on 2022-09-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_teacher_options_teacher_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='prénom'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='nom'),
        ),
    ]
