# Generated by Django 4.1.1 on 2022-10-04 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_alter_teacher_first_name_alter_teacher_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='created_by',
        ),
    ]
