# Generated by Django 4.1.1 on 2022-10-04 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_alter_teacher_managers_remove_teacher_user_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='created_by',
        ),
    ]
