# Generated by Django 4.1.1 on 2022-10-31 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0008_teacher_created_by_teacher_teacher_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='mobile',
        ),
        migrations.AddField(
            model_name='teacher',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+22891036560', max_length=128, region=None, verbose_name='Numéro de téléphone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teacher_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
