# Generated by Django 4.1.1 on 2022-11-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_remove_teacher_mobile_teacher_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assigned_as_teacher',
            field=models.BooleanField(default=False, verbose_name='Assigné comme professeur'),
        ),
    ]
