# Generated by Django 4.1.1 on 2022-11-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_teacher_assigned_as_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='admission_date',
            field=models.DateField(auto_now=True),
        ),
    ]
