# Generated by Django 4.1.1 on 2022-11-14 10:27

import django.core.validators
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('teacher', '0011_teacher_admission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='marksheet',
            field=models.FileField(default='', help_text='Le fichier doit être scanner sous format pdf', upload_to='teachers/applicants/teacher_marksheets/%d/%m/%Y', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Uploader votre dossier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='expertise',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Spécialisations'),
        ),
    ]
