# Generated by Django 4.1.1 on 2022-11-24 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0035_alter_subject_instructor'),
        ('teacher', '0013_teachersubjectgroup'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teachersubjectgroup',
            unique_together={('teacher', 'department', 'ac_session')},
        ),
    ]
