# Generated by Django 4.1.1 on 2022-11-24 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0036_remove_subject_instructor'),
        ('teacher', '0014_alter_teachersubjectgroup_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersubjectgroup',
            name='ac_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academic.academicsession', verbose_name='Session académique'),
        ),
    ]
