# Generated by Django 4.1.1 on 2022-09-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonuserprofile',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='users/cover-pictures', verbose_name='Photo de couverture'),
        ),
        migrations.AddField(
            model_name='commonuserprofile',
            name='headline',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='commonuserprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile-pictures', verbose_name='Photo de profil'),
        ),
    ]
