# Generated by Django 4.1.1 on 2022-11-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_commonuserprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='requested_role',
            field=models.CharField(blank=True, choices=[('subscriber', 'Abonné'), ('student', 'Étudiant'), ('teacher', 'Professeur'), ('editor', 'Editeur'), ('academic_officer', 'Direction Académique'), ('admin', 'Administrateur')], max_length=50, verbose_name='Type de compte demandé'),
        ),
    ]
