# Generated by Django 4.1.1 on 2022-11-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_user_requested_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='requested_role',
            field=models.CharField(choices=[('subscriber', 'Abonné'), ('student', 'Étudiant'), ('teacher', 'Professeur'), ('editor', 'Editeur'), ('academic_officer', 'Direction Académique'), ('admin', 'Administrateur'), ('accounts', 'Comptabilité')], default='subscriber', max_length=50, verbose_name='Type de compte demandé'),
        ),
    ]
