# Generated by Django 4.1.1 on 2022-11-12 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_user_requested_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='employee_or_student_id',
        ),
    ]
