# Generated by Django 4.1.1 on 2022-11-15 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_delete_customgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
