# Generated by Django 4.1.1 on 2022-10-05 10:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0021_delete_schoolfees'),
    ]

    operations = [
        migrations.CreateModel(
            name='schoolFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fees_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant des frais')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic.department')),
                ('semesters', models.ManyToManyField(limit_choices_to=2, to='academic.semester')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
