# Generated by Django 4.1.1 on 2022-10-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0021_delete_schoolfees'),
        ('payment', '0003_schoolfees_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolfees',
            name='semesters',
            field=models.ManyToManyField(blank=True, limit_choices_to=2, to='academic.semester', verbose_name='Semestres'),
        ),
    ]
