# Generated by Django 4.1.1 on 2022-10-05 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0021_delete_schoolfees'),
        ('payment', '0005_alter_schoolfees_semesters'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolfees',
            name='ac_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.academicsession', verbose_name='Session académique'),
        ),
        migrations.AlterField(
            model_name='schoolfees',
            name='fees_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Montant des frais'),
        ),
    ]
