# Generated by Django 4.1.1 on 2022-10-05 14:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_admissionstudent_admission_policy_agreement'),
        ('payment', '0006_schoolfees_ac_session_alter_schoolfees_fees_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fee_to_pay', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Montant à payer')),
                ('paid_fee', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Montant payé')),
                ('owed_fee', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Montant restant')),
                ('fees', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payment.schoolfees', verbose_name='Montant de base')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.student', verbose_name='Etudiant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payement_date', models.DateTimeField(auto_now=True, verbose_name='Date de paiement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.student', verbose_name='Etudiant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
