# Generated by Django 4.1.1 on 2022-10-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_rename_studentfees_studentfeesinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payement_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de paiement'),
        ),
    ]
