# Generated by Django 4.1.1 on 2022-10-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_alter_payment_payement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeesinfo',
            name='fee_to_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='Montant à payer'),
        ),
        migrations.AlterField(
            model_name='studentfeesinfo',
            name='owed_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Montant restant'),
        ),
        migrations.AlterField(
            model_name='studentfeesinfo',
            name='paid_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Montant payé'),
        ),
    ]
