# Generated by Django 4.1.1 on 2022-10-05 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_admissionstudent_religion'),
        ('payment', '0010_alter_studentfeesinfo_fee_to_pay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeesinfo',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_fee', to='student.student', verbose_name='Étudiant'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
