# Generated by Django 4.1.1 on 2022-10-07 21:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_admissionstudent_religion_and_more'),
        ('payment', '0011_alter_studentfeesinfo_student_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeesinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Créer le'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentfeesinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifier le'),
        ),
        migrations.AlterField(
            model_name='studentfeesinfo',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='Étudiant'),
        ),
    ]
