# Generated by Django 4.1.1 on 2022-10-07 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0021_delete_schoolfees'),
        ('payment', '0012_studentfeesinfo_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolfees',
            name='ac_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicsession', verbose_name='Session académique'),
        ),
    ]
