# Generated by Django 4.1.1 on 2022-10-07 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_admissionstudent_religion_and_more'),
        ('payment', '0013_alter_schoolfees_ac_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeesinfo',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='Étudiant'),
        ),
    ]
