# Generated by Django 4.1.1 on 2022-10-09 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0022_academicterm_siteconfig_academicsession_current'),
        ('student', '0014_alter_admissionstudent_religion_and_more'),
        ('payment', '0015_alter_studentfeesinfo_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_from_previous_term', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20)),
                ('semesters', models.ManyToManyField(blank=True, null=True, related_name='semesters', to='academic.semester')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicsession', verbose_name='Année académique')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='Étudiant')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicterm', verbose_name='Tranche')),
            ],
            options={
                'ordering': ['student', 'term'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField()),
                ('date_paid', models.DateField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.invoice')),
            ],
        ),
        migrations.RemoveField(
            model_name='studentfeesinfo',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='studentfeesinfo',
            name='student',
        ),
        migrations.DeleteModel(
            name='schoolFees',
        ),
        migrations.DeleteModel(
            name='StudentFeesInfo',
        ),
    ]
