# Generated by Django 4.1.1 on 2022-10-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0022_academicterm_siteconfig_academicsession_current'),
        ('payment', '0016_invoice_invoiceitem_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='semesters',
            field=models.ManyToManyField(null=True, related_name='semesters', to='academic.semester', verbose_name='Semestres'),
        ),
    ]
