# Generated by Django 4.1.1 on 2022-10-11 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_alter_invoice_term_alter_receipt_amount_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='semesters',
        ),
    ]
