# Generated by Django 4.1.1 on 2022-10-16 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0019_remove_invoice_semesters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['student', 'session']},
        ),
    ]
