# Generated by Django 4.1.1 on 2022-10-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='term1',
            field=models.IntegerField(default=0, verbose_name='Première tranche'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='term2',
            field=models.IntegerField(default=0, verbose_name='Deuxième tranche'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='term3',
            field=models.IntegerField(default=0, verbose_name='Troisième tranche'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='term4',
            field=models.IntegerField(default=0, verbose_name='Quatrième tranche'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='amount',
            field=models.IntegerField(verbose_name='Montant'),
        ),
    ]
