# Generated by Django 4.1.1 on 2022-10-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0021_invoiceitem_term1_invoiceitem_term2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='balance_from_previous_term',
            field=models.IntegerField(default=0),
        ),
    ]
