# Generated by Django 4.1.1 on 2022-10-27 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_inscription'),
        ('academic', '0030_level_class'),
        ('payment', '0023_rename_balance_from_previous_term_invoice_balance_from_previous_session'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('student', 'session')},
        ),
    ]
