# Generated by Django 4.1.1 on 2022-11-07 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0024_alter_invoice_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=set(),
        ),
    ]
