# Generated by Django 4.1.1 on 2022-11-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0025_alter_invoice_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Clôturer')], default='active', max_length=20),
        ),
    ]
