# Generated by Django 4.1.1 on 2022-11-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0026_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='term1',
            field=models.IntegerField(default=0, verbose_name='Première tranche'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='term2',
            field=models.IntegerField(default=0, verbose_name='Deuxième tranche'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='term3',
            field=models.IntegerField(default=0, verbose_name='Troisième tranche'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='term4',
            field=models.IntegerField(default=0, verbose_name='Quatrième tranche'),
        ),
    ]
