# Generated by Django 4.1.1 on 2022-09-13 19:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempSerialID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('serial', models.CharField(blank=True, max_length=50, verbose_name='Numéro de série')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_serials', to='academic.department', verbose_name='Département')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
