# Generated by Django 4.1.1 on 2022-09-15 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_tempserialid_student_tempserialid_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='current_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_batches', to='academic.batch', verbose_name='Promotion actuelle'),
        ),
    ]
