# Generated by Django 4.1.1 on 2022-09-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_alter_department_current_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_code',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='Code cours'),
        ),
    ]
