# Generated by Django 4.1.1 on 2022-09-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_alter_subject_subject_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code cours'),
        ),
    ]
