# Generated by Django 4.1.1 on 2022-09-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_alter_subject_subject_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='practical_marks',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='theory_marks',
        ),
    ]
