# Generated by Django 4.1.1 on 2022-09-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_remove_subject_practical_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='class_marks',
            field=models.FloatField(blank=True, null=True, verbose_name='Note de classe'),
        ),
        migrations.AddField(
            model_name='subject',
            name='exam_marks',
            field=models.FloatField(blank=True, null=True, verbose_name="Note d'examen"),
        ),
        migrations.AddField(
            model_name='subject',
            name='extra_marks',
            field=models.FloatField(blank=True, null=True, verbose_name='Note de rattrapage'),
        ),
    ]
