# Generated by Django 4.1.1 on 2022-09-24 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_subject_class_marks_subject_exam_marks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='class_marks',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='exam_marks',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='extra_marks',
        ),
    ]
