# Generated by Django 4.1.1 on 2022-09-26 22:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_remove_subject_class_marks_remove_subject_exam_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Créer le'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifier le'),
        ),
        migrations.AddField(
            model_name='batch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Créer le'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifier le'),
        ),
        migrations.AddField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Créer le'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifier le'),
        ),
        migrations.AddField(
            model_name='semester',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Créer le'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifier le'),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Créer le'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifier le'),
        ),
        migrations.AddField(
            model_name='tempserialid',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Créer le'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tempserialid',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifier le'),
        ),
    ]
