# Generated by Django 4.1.1 on 2022-09-26 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0014_batch_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicsession', verbose_name='Année scolaire'),
        ),
    ]
