# Generated by Django 4.1.1 on 2022-09-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0015_alter_batch_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Opérationnel'),
        ),
    ]
