# Generated by Django 4.1.1 on 2022-09-27 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0016_semester_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='active',
        ),
    ]
