# Generated by Django 4.1.1 on 2022-10-04 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0017_remove_semester_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='created_by',
        ),
    ]
