# Generated by Django 4.1.1 on 2022-10-05 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0020_schoolfees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='schoolFees',
        ),
    ]
