# Generated by Django 4.1.1 on 2022-10-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0021_delete_schoolfees'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('current', models.BooleanField(default=True, verbose_name='Tranche courante')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='academicsession',
            name='current',
            field=models.BooleanField(default=True, verbose_name='Marquer comme année courante'),
        ),
    ]
