# Generated by Django 4.1.1 on 2022-10-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0022_academicterm_siteconfig_academicsession_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicterm',
            name='current',
            field=models.BooleanField(default=True, verbose_name='Période courante'),
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nom'),
        ),
    ]
