# Generated by Django 4.1.1 on 2022-10-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0022_academicterm_siteconfig_academicsession_current'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='batch',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='department',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='year',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='created_by',
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'Promotions'},
        ),
        migrations.AddField(
            model_name='department',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Frais de scolarité'),
        ),
        migrations.AddField(
            model_name='department',
            name='level',
            field=models.CharField(choices=[('lp1', 'LP1'), ('lp2', 'LP2'), ('lp3', 'LP3'), ('m1', 'M1'), ('m2', 'M2')], default='LP1', max_length=3, verbose_name='Niveau'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'code', 'level')},
        ),
    ]
