# Generated by Django 4.1.1 on 2022-10-11 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_alter_student_options_remove_regularstudent_semester_and_more'),
        ('academic', '0024_alter_batch_unique_together_remove_batch_created_by_and_more'),
        ('result', '0018_alter_result_unique_together_and_more'),
        ('payment', '0019_remove_invoice_semesters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.RemoveField(
            model_name='department',
            name='batches',
        ),
        migrations.RemoveField(
            model_name='department',
            name='current_batch',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
