# Generated by Django 4.1.1 on 2022-10-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0025_delete_semester_remove_department_batches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default='True', verbose_name='Actif'),
        ),
    ]
