# Generated by Django 4.1.1 on 2022-10-27 10:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0029_alter_department_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('level', models.CharField(choices=[('lp1', 'LP1'), ('lp2', 'LP2'), ('lp3', 'LP3'), ('m1', 'M1'), ('m2', 'M2')], default='LP1', max_length=3, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, help_text='Ecriver une simple description a propos du niveau', null=True, verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('ac_session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic.academicsession', verbose_name='Année académique')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic.department', verbose_name='Filière')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic.level', verbose_name='Niveau')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
