# Generated by Django 4.1.1 on 2022-10-27 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0027_delete_inscription'),
        ('academic', '0030_level_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
