# Generated by Django 4.1.1 on 2022-11-01 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0031_delete_class_delete_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='department',
            name='updated_at',
        ),
    ]
