# Generated by Django 4.1.1 on 2022-11-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0032_delete_academicterm_remove_department_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicsession',
            name='year',
            field=models.PositiveIntegerField(unique=True, verbose_name='Année académique'),
        ),
    ]
