# Generated by Django 4.1.1 on 2022-11-24 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_teacher_marksheet_alter_teacher_expertise'),
        ('academic', '0034_subject_hourly_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacher', verbose_name='Professeur'),
        ),
    ]
