# Generated by Django 4.1.1 on 2022-11-24 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0035_alter_subject_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='instructor',
        ),
    ]
