# Generated by Django 4.1.1 on 2022-09-13 19:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0002_teacher_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0004_tempserialid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(max_length=100, verbose_name='Noms')),
                ('last_name', models.CharField(max_length=100, verbose_name='Prénoms')),
                ('photo', models.ImageField(upload_to='students/applicant/')),
                ('fathers_first_name', models.CharField(max_length=100, verbose_name='Nom du père')),
                ('fathers_last_name', models.CharField(max_length=100, verbose_name='Prénom du père')),
                ('fathers_mobile_number', models.CharField(max_length=20, verbose_name='Numéro de téléphone du père')),
                ('mothers_first_name', models.CharField(max_length=100, verbose_name='Nom de la mère')),
                ('mothers_last_name', models.CharField(max_length=100, verbose_name='Prénom de la mère')),
                ('mothers_mobile_number', models.CharField(max_length=100, verbose_name='Numéro de téléphone de la mère')),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin'), ('N', 'Autre')], max_length=15, verbose_name='Sexe')),
                ('nationality', django_countries.fields.CountryField(max_length=2, null=True, verbose_name='Nationalité')),
                ('current_address', models.TextField(verbose_name='Adresse courante')),
                ('permanent_address', models.TextField(blank=True, null=True, verbose_name='Adresse permanente')),
                ('mobile_number', models.CharField(max_length=11, verbose_name='Numéro de téléphone')),
                ('guardian_mobile_number', models.CharField(max_length=20, verbose_name='Numéro Personne à prévenir')),
                ('bac_passing_year', models.CharField(max_length=4, verbose_name="Année d'obtention du BAC")),
                ('bac_marksheet', models.FileField(help_text='Le fichier doit être scanner sous format pdf', upload_to='students/applicants/bac_marksheets/%d/%m/%Y', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Uploader votre relevé de BAC')),
                ('last_exam_name', models.CharField(blank=True, choices=[('L', 'Licence'), ('M', 'Master'), ('D', 'Doctorat'), ('', 'Aucun')], help_text='Concerne les diplômes après le BAC', max_length=1, null=True, verbose_name='Nom du dernier diplôme obtenu')),
                ('last_exam_marksheet', models.FileField(blank=True, help_text='Le fichier doit être scanner sous format pdf', null=True, upload_to='students/applicants/last_marksheets/%d/%m/%Y', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Uploader votre dernier diplôme')),
                ('admission_policy_agreement', models.BooleanField(default=False, verbose_name='\n        এই মর্মে অঙ্গীকার করছি যে, ভর্তি হওয়ার সুযোগ পেলে আমি অত্র শিক্ষা প্রতিষ্ঠান ও \n        বাংলাদেশ কারিগরি শিক্ষা বোর্ডের যাবতীয় আইনকানুন মেনে চলব এবং কোন অবস্থাতেই অত্র শিক্ষা প্রতিষ্ঠান, বাংলাদেশ কারিগরি শিক্ষা বোর্ড \n        এবং দেশের আইনের পরিপন্থি কোন কাজে লিপ্ত হব না\n        ')),
                ('admitted', models.BooleanField(default=False, verbose_name='Accepté')),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name="Date d'acceptation")),
                ('paid', models.BooleanField(default=False, verbose_name='Payé')),
                ('application_type', models.CharField(choices=[('1', 'En ligne'), ('2', 'Hors ligne')], default='1', max_length=1, verbose_name="Type d'application")),
                ('migration_status', models.CharField(blank=True, max_length=255, null=True)),
                ('rejected', models.BooleanField(default=False, verbose_name='Rejeté')),
                ('assigned_as_student', models.BooleanField(default=False, verbose_name='Assigné comme étudiant')),
                ('choosen_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission_students', to='academic.department', verbose_name='Département choisi')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('roll', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('temp_serial', models.CharField(blank=True, max_length=50, null=True)),
                ('temporary_id', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian_mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('is_alumni', models.BooleanField(default=False)),
                ('is_dropped', models.BooleanField(default=False)),
                ('ac_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.academicsession')),
                ('admission_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.admissionstudent')),
                ('admitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academic.batch')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.semester')),
            ],
            options={
                'ordering': ['semester', 'roll', 'registration_number'],
            },
        ),
        migrations.CreateModel(
            name='RegularStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CounselingComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('comment', models.CharField(max_length=150, verbose_name='Commentaire')),
                ('counselor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Conseiller')),
                ('registrant_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.admissionstudent', verbose_name='Étudiant à inscrire')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='counsel_comment',
            field=models.ManyToManyField(blank=True, to='student.counselingcomment', verbose_name='Commentaires du conseille'),
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='counseling_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counselors', to='teacher.teacher', verbose_name='Conseiller par'),
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='department_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.department', verbose_name='Choix du département'),
        ),
    ]
