# Generated by Django 4.1.1 on 2022-09-13 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_tempserialid_student_tempserialid_year'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['semester', 'registration_number']},
        ),
        migrations.RemoveField(
            model_name='student',
            name='roll',
        ),
        migrations.AlterField(
            model_name='regularstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='Étudiant'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ac_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.academicsession', verbose_name='Session académique'),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academic.batch', verbose_name='Promotion'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Numéro de personne à prévenir'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_alumni',
            field=models.BooleanField(default=False, verbose_name='Ancien élève ?'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_dropped',
            field=models.BooleanField(default=False, verbose_name="A quitté l'école ?"),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name="Numéro d'enregistrement"),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.semester', verbose_name='Semestre'),
        ),
        migrations.AlterField(
            model_name='student',
            name='temp_serial',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de série'),
        ),
        migrations.AlterField(
            model_name='student',
            name='temporary_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Id'),
        ),
    ]
