# Generated by Django 4.1.1 on 2022-09-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_options_remove_student_roll_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['semester', 'roll', 'registration_number']},
        ),
        migrations.AddField(
            model_name='student',
            name='roll',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='counsel_comment',
            field=models.ManyToManyField(blank=True, to='student.counselingcomment', verbose_name='Commentaires du conseil'),
        ),
    ]
