# Generated by Django 4.1.1 on 2022-09-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_options_student_roll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionstudent',
            name='admission_policy_agreement',
            field=models.BooleanField(default=False, verbose_name='\n        Accepter les conditions\n        '),
        ),
    ]
