# Generated by Django 4.1.1 on 2022-09-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_admissionstudent_admission_policy_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionstudent',
            name='counsel_comment',
            field=models.ManyToManyField(blank=True, to='student.counselingcomment', verbose_name='Commentaire du conseil'),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='fathers_first_name',
            field=models.CharField(max_length=100, verbose_name='Prénom du père'),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='fathers_last_name',
            field=models.CharField(max_length=100, verbose_name='Nom du père'),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='mothers_first_name',
            field=models.CharField(max_length=100, verbose_name='Prénom de la mère'),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='mothers_last_name',
            field=models.CharField(max_length=100, verbose_name='Nom de la mère'),
        ),
        migrations.AlterField(
            model_name='counselingcomment',
            name='comment',
            field=models.CharField(max_length=150, verbose_name='Commentaire du conseil'),
        ),
    ]
