# Generated by Django 4.1.1 on 2022-09-27 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_admissionstudent_counsel_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionstudent',
            name='admission_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
