# Generated by Django 4.1.1 on 2022-09-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_admissionstudent_admission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionstudent',
            name='admission_date',
            field=models.DateField(auto_now=True),
        ),
    ]
