# Generated by Django 4.1.1 on 2022-10-04 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0007_alter_admissionstudent_admission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
