# Generated by Django 4.1.1 on 2022-10-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_student_student_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionstudent',
            name='admission_policy_agreement',
            field=models.BooleanField(verbose_name='\n        Accepter les conditions\n        '),
        ),
    ]
