# Generated by Django 4.1.1 on 2022-10-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_remove_admissionstudent_department_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionstudent',
            name='religion',
            field=models.CharField(default='islam', max_length=30, verbose_name='Religion'),
            preserve_default=False,
        ),
    ]
