# Generated by Django 4.1.1 on 2022-10-07 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0013_admissionstudent_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionstudent',
            name='religion',
            field=models.CharField(choices=[('islam', 'islam'), ('christianisme', 'christianisme'), ('animisme', 'animisme'), ('athéisme', 'athéisme'), ('autre', 'autre')], max_length=30, verbose_name='Religion'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
