# Generated by Django 4.1.1 on 2022-10-11 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_alter_admissionstudent_fathers_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['roll', 'registration_number']},
        ),
        migrations.RemoveField(
            model_name='regularstudent',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='student',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
    ]
