# Generated by Django 4.1.1 on 2022-10-13 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0026_department_is_active'),
        ('student', '0018_alter_student_options_remove_regularstudent_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionstudent',
            name='department_choice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academic.department', verbose_name='Choix du département'),
            preserve_default=False,
        ),
    ]
