# Generated by Django 4.1.1 on 2022-10-14 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_admissionstudent_department_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.admissionstudent', unique_for_year=True),
        ),
    ]
