# Generated by Django 4.1.1 on 2022-10-16 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0028_alter_department_options_alter_department_code_and_more'),
        ('student', '0020_alter_student_admission_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assign_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='choosen_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission_students', to='academic.department', verbose_name='Filière choisie'),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='department_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.department', verbose_name='Choix de la filière'),
        ),
    ]
