# Generated by Django 4.1.1 on 2022-10-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_student_assign_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionstudent',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Date de naissance'),
        ),
    ]
