# Generated by Django 4.1.1 on 2022-10-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_alter_admissionstudent_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_account',
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date de naissance'),
        ),
    ]
