# Generated by Django 4.1.1 on 2022-10-23 14:46

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_admissionstudent_student_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionstudent',
            name='fathers_mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Numéro de téléphone du père'),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='mothers_mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Numéro de téléphone de la mère'),
        ),
    ]
