# Generated by Django 4.1.1 on 2022-10-27 10:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0030_level_class'),
        ('student', '0025_alter_admissionstudent_fathers_mobile_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic.class')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
