# Generated by Django 4.1.1 on 2022-10-27 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_inscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inscription',
        ),
    ]
