# Generated by Django 4.1.1 on 2022-10-27 11:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0031_delete_class_delete_level'),
        ('student', '0027_delete_inscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionstudent',
            name='last_exam_name',
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='last_exam_marksheet',
            field=models.FileField(blank=True, help_text='Le fichier doit être scanner sous format pdf', null=True, upload_to='students/applicants/last_marksheets/%d/%m/%Y', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Autre document'),
        ),
        migrations.CreateModel(
            name='StudentInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('registration_number', models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name="Numéro d'enregistrement")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créer le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifier le')),
                ('ac_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.academicsession', verbose_name='Session académique')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.department', verbose_name='Filière choisie')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student', unique_for_year=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
