# Generated by Django 4.1.1 on 2022-10-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_student_first_inscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.RemoveField(
            model_name='student',
            name='assign_payment',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_mobile',
        ),
        migrations.RemoveField(
            model_name='student',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='roll',
        ),
        migrations.AddField(
            model_name='studentinscription',
            name='assign_payment',
            field=models.BooleanField(default=False),
        ),
    ]
