# Generated by Django 4.1.1 on 2022-10-27 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0030_alter_student_options_remove_student_assign_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinscription',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student.student', unique_for_year=True),
        ),
    ]
