# Generated by Django 4.1.1 on 2022-10-27 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0031_alter_studentinscription_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinscription',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='student.student', unique_for_year=True),
        ),
    ]
