# Generated by Django 4.1.1 on 2022-10-27 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0032_alter_studentinscription_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['roll', 'registration_number']},
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_inscription',
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='last_exam_name',
            field=models.CharField(blank=True, choices=[('L', 'Licence'), ('M', 'Master'), ('D', 'Doctorat'), ('', 'Aucun')], help_text='Concerne les diplômes après le BAC', max_length=1, null=True, verbose_name='Nom du dernier diplôme obtenu'),
        ),
        migrations.AddField(
            model_name='student',
            name='assign_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Numéro de personne à prévenir'),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_number',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name="Numéro d'enregistrement"),
        ),
        migrations.AddField(
            model_name='student',
            name='roll',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='last_exam_marksheet',
            field=models.FileField(blank=True, help_text='Le fichier doit être scanner sous format pdf', null=True, upload_to='students/applicants/last_marksheets/%d/%m/%Y', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Uploader votre dernier diplôme'),
        ),
        migrations.DeleteModel(
            name='StudentInscription',
        ),
    ]
