# Generated by Django 4.1.1 on 2022-10-31 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0031_delete_class_delete_level'),
        ('student', '0035_alter_student_admission_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionstudent',
            name='choosen_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission_students', to='academic.department', verbose_name='Filière courante'),
        ),
    ]
