# Generated by Django 4.1.1 on 2022-11-04 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0036_alter_admissionstudent_choosen_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionstudent',
            name='student_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
