# Generated by Django 4.1.1 on 2022-11-04 23:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0037_alter_admissionstudent_student_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionstudent',
            name='last_exam_name',
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='last_exam_marksheet',
            field=models.FileField(blank=True, help_text='Le fichier doit être scanner sous format pdf', null=True, upload_to='students/applicants/last_marksheets/%d/%m/%Y', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Autre document'),
        ),
    ]
