# Generated by Django 4.1.1 on 2022-11-08 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0032_delete_academicterm_remove_department_created_at_and_more'),
        ('student', '0038_remove_admissionstudent_last_exam_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionstudent',
            name='ac_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.academicsession', verbose_name='Session académique'),
        ),
    ]
