# Generated by Django 4.1.1 on 2022-11-08 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0039_admissionstudent_ac_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='guardian_mobile',
        ),
    ]
