# Generated by Django 4.1.1 on 2022-11-08 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0040_remove_student_guardian_mobile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.RemoveField(
            model_name='student',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='roll',
        ),
    ]
