# Generated by Django 4.1.1 on 2022-11-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0041_alter_student_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegularStudent',
        ),
    ]
