# Generated by Django 4.1.1 on 2022-11-20 08:54

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0042_delete_regularstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionstudent',
            name='student_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='student.student'),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='fathers_mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Exemple +2289XXXXX', max_length=128, null=True, region=None, verbose_name='Numéro de téléphone du père'),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='guardian_mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Exemple +2289XXXXX', max_length=128, region=None, verbose_name='Numéro Personne à prévenir'),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Exemple +2289XXXXX', max_length=128, region=None, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='mothers_mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Exemple +2289XXXXX', max_length=128, null=True, region=None, verbose_name='Numéro de téléphone de la mère'),
        ),
    ]
