# Generated by Django 4.1.1 on 2022-12-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0036_remove_subject_instructor'),
        ('student', '0043_admissionstudent_student_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionstudent',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('N', 'Autre')], max_length=15, verbose_name='Sexe'),
        ),
        migrations.AlterUniqueTogether(
            name='admissionstudent',
            unique_together={('last_name', 'first_name', 'ac_session', 'date_of_birth', 'email')},
        ),
    ]
